name: Build
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        repository: iamhimansu/go
        token: ${{ secrets.GITHUB_TOKEN }}
        ssh-strict: true
        persist-credentials: true
        clean: true
        fetch-depth: 1
        lfs: false
        submodules: false
        set-safe-directory: true
        
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17
      id: go
        
    - name: Build
      run: go build .
    
    - name: Test
      run: go test -v ./...
