name: Build and Deploy Go App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GOROOT: /usr/local/go
      GOPATH: /go/src/github.com/iamhimansu/firstapp/main.go
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build Go app
      run: go build -o app go/src/github.com/iamhimansu/firstapp/main.go
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        publish_dir: ./public
