name: Go

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - uses: actions/checkout@v2
      with:
        ref: main
    - name: Build
      run: go build
