name: Build and Deploy Go Binary

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Go binary
      run: |
        go build -o myapp main.go
        ls

    - name: Upload binary as artifact
      uses: actions/upload-artifact@v2
      with:
        name: myapp
        path: myapp

  run:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download binary artifact
      uses: actions/download-artifact@v2
      with:
        name: myapp
    - name: List files
      run: ls
      
    - name: Make binary executable
      run: |
        cd /home/runner/work/go/go
        ls
        chmod +x myapp
        ls

    - name: Run binary
      run: |
        cd /home/runner/work/go/go
        ./myapp
